const products = [
    {
        _id: '1',
        name: 'Large Wool-blend Rug',
        image: '/images/rug.jpg',
        description:'Large, patterned rug in a wool and cotton blend with soft, cozy pile for a warm, comfortable atmosphere in your home.',
        brand: 'Hm',
        category: 'Rugs',
        price: 631.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
      },
      {
        _id: '2',
        name: 'Metal Table Lamp',
        image: '/images/lamp.jpg',
        description:
        'Table lamp in lacquered metal with a modern design and an rounded lampshade to spread warm, diffused light. Matching, fabric-covered cord with a plastic switch and G9 bulb holder. Max 4 W LED. Bulb not included. Diameter of lampshade 14 1/2 in. Total height 14 1/2 in.',
        brand: 'Hm',
        category: 'Lighting',
        price: 89.99,
        countInStock: 7,
        rating: 4.0,
        numReviews: 8,
      },
      {
        _id: '3',
        name: 'Footed Stoneware Bowl',
        image: '/images/bowl.jpg',
        description:
        'Bowl in glazed stoneware with a matte finish and three chunky legs. Height 5 1/2 in. Diameter 9 3/4 in.',
        brand: 'Hm',
        category: 'Decorations',
        price: 42.99,
        countInStock: 5,
        rating: 3,
        numReviews: 12,
      },
      {
        _id: '4',
        name: 'Stoneware Bookendboo',
        image: '/images/bookend.jpg',
        description:
        'Bookend in glazed stoneware with rounded, abstract shapes to add a contemporary touch to your home decor. Depth 3 3/4 in. Width 4 1/4 in. Height approx. 7 in.',
        brand: 'Hm',
        category: 'Books',
        price: 26.99,
        countInStock: 11,
        rating: 5,
        numReviews: 12,
      },
      {
        _id: '5',
        name: 'Patterned King/Queen Duvet Cover Set',
        image: '/images/coverset.jpg',
        description:
'King/queen duvet cover set in woven, gingham cotton fabric. Duvet cover fastens at foot end with concealed metal snap fasteners. Two pillowcases with envelope opening. Thread count 144.',
        brand: 'Hm',
        category: 'Bedding',
        price: 64.99,
        countInStock: 7,
        rating: 3.5,
        numReviews: 10,
      },
      {
        _id: '6',
        name: 'Wavy Metal Candelabrach',
        image: '/images/candel.jpg',
        description:
        'Candelabra in metal with a stylish, matte finish. Wavy design with five arms in different heights. Depth 5 in. Height at highest point approx. 8 3/4 in.',
        brand: 'Hm',
        category: 'Decorations',
        price: 31.99,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
      },
]

export default products;
